### ISSUE TITLE
したらばの監視が思い通りに動いてない？件について

### ISSUE THREAD

**Issue by japankun** [japankun/bbs.jpnkn.com#47]
Actionsで以下のように5分に一回接続チェックが走るようになっている。
```
on:
  push:
  schedule:
  - cron: "*/5 * * * *"
```
なんだけど、少し前から30分に一回の実行になってしまっていて
サーバーステータスにエラー表示は出たままになるので直したい。
